# Generated by Django 5.2.4 on 2025-08-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='chunks_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='embedding_file_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='embedding_model',
            field=models.CharField(default='text-embedding-3-small', max_length=50),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='status',
            field=models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('embedding', 'Creating Embeddings'), ('completed', 'Completed'), ('error', 'Error')], default='uploading', max_length=20),
        ),
    ]
