# Generated by Django 5.2.4 on 2025-08-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_file_based_embeddings'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
