# Generated by Django 5.2.4 on 2025-08-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_knowledgebase_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiassistant',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('ms', 'Bahasa Malaysia')], default='en', max_length=2),
        ),
    ]
