# Generated by Django 5.2.4 on 2025-08-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile_apiusagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'Regular User')], default='user', max_length=10),
        ),
    ]
