# Generated by Django 5.2.4 on 2025-08-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_populate_business_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Plan name (e.g., 'free', 'pro', 'enterprise')", max_length=50, unique=True)),
                ('display_name', models.CharField(help_text='Display name for the plan', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Plan description')),
                ('monthly_api_limit', models.IntegerField(default=1000, help_text='Monthly API request limit (0 = unlimited)')),
                ('monthly_token_limit', models.IntegerField(default=50000, help_text='Monthly token limit (0 = unlimited)')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly price in USD', max_digits=10)),
                ('features', models.JSONField(blank=True, default=list, help_text='List of plan features')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default plan for new users')),
                ('sort_order', models.IntegerField(default=0, help_text='Order for displaying plans')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
