# Generated by Django 5.2.4 on 2025-08-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_subscriptionplan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Subscription Plan', 'verbose_name_plural': 'Subscription Plans'},
        ),
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='sort_order',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='display_name',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_assistants',
            field=models.IntegerField(default=1, help_text='Maximum AI assistants allowed'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_knowledge_bases',
            field=models.IntegerField(default=1, help_text='Maximum knowledge bases allowed'),
        ),
    ]
