# Generated by Django 5.2.4 on 2025-08-07 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_subscriptionplan_options_and_more'),
    ]

    operations = [
    ]
