# Generated by Django 5.2.4 on 2025-08-07 11:16

from django.db import migrations


def create_default_subscription_plans(apps, schema_editor):
    """Create default subscription plans"""
    SubscriptionPlan = apps.get_model('core', 'SubscriptionPlan')
    
    # Delete existing plans (for clean setup)
    SubscriptionPlan.objects.all().delete()
    
    # Create Free Plan (default)
    SubscriptionPlan.objects.create(
        name='free',
        description='Perfect for getting started with AI assistants',
        monthly_api_limit=1000,
        monthly_token_limit=50000,
        max_assistants=1,
        max_knowledge_bases=1,
        price=0.00,
        features=[
            'Basic AI Assistant',
            'Email Support',
            '1,000 API requests/month',
            '50,000 tokens/month',
            '1 Knowledge Base'
        ],
        order=1,
        is_active=True,
        is_default=True
    )
    
    # Create Pro Plan
    SubscriptionPlan.objects.create(
        name='pro',
        description='Advanced features for power users and small teams',
        monthly_api_limit=10000,
        monthly_token_limit=500000,
        max_assistants=5,
        max_knowledge_bases=3,
        price=29.99,
        features=[
            'Advanced AI Assistant',
            'Priority Support',
            '10,000 API requests/month',
            '500,000 tokens/month',
            '5 AI Assistants',
            '3 Knowledge Bases',
            'Custom Training Data',
            'API Access'
        ],
        order=2,
        is_active=True
    )
    
    # Create Pro+ Plan
    SubscriptionPlan.objects.create(
        name='pro_plus',
        description='Enterprise-grade solution for businesses',
        monthly_api_limit=50000,
        monthly_token_limit=2000000,
        max_assistants=20,
        max_knowledge_bases=10,
        price=99.99,
        features=[
            'Enterprise AI Assistant',
            '24/7 Premium Support',
            '50,000 API requests/month',
            '2,000,000 tokens/month',
            '20 AI Assistants',
            '10 Knowledge Bases',
            'Custom Training Data',
            'Full API Access',
            'White-label Options',
            'Dedicated Account Manager',
            'SLA Guarantee'
        ],
        order=3,
        is_active=True
    )


def reverse_default_subscription_plans(apps, schema_editor):
    """Remove default subscription plans"""
    SubscriptionPlan = apps.get_model('core', 'SubscriptionPlan')
    SubscriptionPlan.objects.filter(name__in=['free', 'pro', 'pro_plus']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20250807_1116'),
    ]

    operations = [
        migrations.RunPython(
            create_default_subscription_plans,
            reverse_default_subscription_plans
        ),
    ]
