# Generated by Django 5.2.4 on 2025-08-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_create_default_subscription_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='source',
            field=models.CharField(choices=[('test_chat', 'Test Chat'), ('test_voice_realtime', 'Test Voice Realtime'), ('widget_chat', 'Widget Chat'), ('widget_voice', 'Widget Voice')], default='test_chat', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='openai_thread_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
