# Generated by Django 5.2.4 on 2025-08-11 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_source_to_chatsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nama konfigurasi widget', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Deskripsi konfigurasi')),
                ('widget_title', models.CharField(default='AI Assistant', max_length=100)),
                ('widget_position', models.CharField(default='bottom-right', max_length=20)),
                ('primary_color', models.CharField(default='#007bff', max_length=7)),
                ('secondary_color', models.CharField(default='#6c757d', max_length=7)),
                ('welcome_message', models.TextField(default='Hello! How can I help you today?')),
                ('chat_placeholder', models.CharField(default='Type your message...', max_length=100)),
                ('voice_enabled', models.BooleanField(default=False)),
                ('voice_language', models.CharField(default='auto', max_length=5)),
                ('voice_show_transcript', models.BooleanField(default=True)),
                ('consent_required', models.BooleanField(default=False)),
                ('consent_title', models.CharField(default='Terms and Conditions', max_length=100)),
                ('consent_content', models.TextField(default='By using this chat, you agree to our terms of service.')),
                ('generated_code', models.TextField(blank=True, help_text='Generated widget HTML/JS code')),
                ('times_copied', models.IntegerField(default=0)),
                ('last_copied_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widget_configs', to='core.aiassistant')),
            ],
            options={
                'verbose_name': 'Widget Configuration',
                'verbose_name_plural': 'Widget Configurations',
                'ordering': ['-updated_at'],
            },
        ),
    ]
