# Generated by Django 5.2.4 on 2025-08-14 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_widget_configuration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WidgetConfiguration',
        ),
    ]
